# This file contains all available configuration options
# with their default values.

run:
  # Timeout for analysis, e.g. 30s, 5m.
  timeout: 5m

output:
  formats:
    - format: colored-line-number

linters:
  enable-all: true
  disable:
    - cyclop # Disabled length/complexity linters.
    - depguard # Enable with settings for required guards.
    - err113 # No way to feasibly follow this in many cases.
    - exhaustruct # Enable for certain files if needed.
    - exportloopref # Replaced by copyloopvar.
    - forbidigo # Enable with settings for required guards.
    - funlen # Disabled length/complexity linters.
    - goimports # Using gci instead.
    - ginkgolinter # Enable if using Ginkgo.
    - gochecknoglobals # Useful in some cases.
    - gochecknoinits # Useful in some cases.
    - gocognit # Disabled length/complexity linters.
    - gocyclo # Disabled length/complexity linters.
    - godox # Prevents TODO/BUG/FIXME.
    - loggercheck # Using sloglint instead.
    - mnd # Sometimes more readable.
    - tagliatelle # Enable if standards are known.
    - varnamelen # Disabled length/complexity linters.
    - wsl # Way too annoying to deal with.

linters-settings:
  misspell:
    locale: US

  exhaustive:
    default-signifies-exhaustive: true

  gci:
    sections:
      - standard
      - default
      - blank
      - dot
      - alias
      - localmodule

  wsl:
    force-err-cuddling: true
    force-case-trailing-whitespace: 2

  whitespace:
    multi-if: true
    multi-func: true

  govet:
    enable-all: true
    disable:
      - shadow

  usetesting:
    os-temp-dir: true

  testifylint:
    enable-all: true
    expected-actual:
      pattern: ^want

  sloglint:
    attr-only: true
    static-msg: true
    args-on-sep-lines: true
    key-naming-case: snake
    context: scope
    forbidden-keys:
      - time
      - level
      - msg

  gofmt:
    simplify: true
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'

  gofumpt:
    extra-rules: true

  godot:
    scope: all
    period: true
    capital: true

  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - promlinter
        - godot
    - source: "^// http(s)?://([^\\s]*)$"
      linters:
        - lll
    - source: "`$"
      linters:
        - lll
    - source: "^\\) .+ \\{$"
      linters:
        - whitespace
