# yaml-language-server: $schema=https://json.schemastore.org/lefthook.json

pre-commit:
  commands:
    pre-commit:
      run: dagger check test lint lint-prettier

commit-msg:
  commands:
    conform:
      run: dagger call lint-commit-msg --msg-file={1}
