# yaml-language-server: $schema=https://json.schemastore.org/lefthook.json

pre-commit:
  commands:
    pre-commit:
      run: dagger --silent check

commit-msg:
  commands:
    commitlint:
      run: dagger --silent call commitlint lint --source=. --msg-file={1}
