# yaml-language-server: $schema=https://json.schemastore.org/lefthook.json

pre-commit:
  commands:
    pre-commit:
      run: dagger --silent check

commit-msg:
  commands:
    conform:
      run: dagger --silent call lint-commit-msg --msg-file={1}
