# yaml-language-server: $schema=https://json.schemastore.org/lefthook.json

pre-commit:
  commands:
    pre-commit:
      run: dagger --progress=logs check

commit-msg:
  commands:
    commitlint:
      run: dagger --progress=logs call commitlint lint --source=. --msg-file={1}
